baseURL = "https://duddomx.github.io"
languageCode = "it"
title = "Note Scritte"
theme = "paper"

[menu]

  [[menu.main]]
    identifier = "Posts"
    name = "Posts"
    pre = "<i class='fa fa-road'></i>"
    url = "/posts/"
    weight = -100